---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud Lab - EBS Backup
Parameters:
  InstanceType:
    Description: Backup EC2 instance type
    Type: String
    Default: t2.nano
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-f5f41398
    us-west-1:
      HVM64: ami-6e84fa0e
    us-west-2:
      HVM64: ami-d0f506b0
    eu-west-1:
      HVM64: ami-b0ac25c3
    eu-central-1:
      HVM64: ami-d3c022bc
    ap-southeast-1:
      HVM64: ami-1ddc0b7e
    ap-northeast-1:
      HVM64: ami-29160d47
    ap-northeast-2:
      HVM64: ami-cf32faa1
    ap-southeast-2:
      HVM64: ami-0c95b86f
    sa-east-1:
      HVM64: ami-fb890097
    cn-north-1:
      HVM64: ami-05a66c68
  SubnetConfig:
    VPC:
      CIDR: 10.44.0.0/16
    Public:
      CIDR: 10.44.0.0/24
Resources:
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: backupEbs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
            - arn:aws:s3:::<%-labWorkBucket%>
            - arn:aws:s3:::<%-labWorkBucket%>/*
          - Effect: Allow
            Action: cloudformation:DeleteStack
            Resource:
              Ref: AWS::StackId
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:lambda:'
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":function:AWSCloudLabTerminator"
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:DetachVolume
            - ec2:DescribeInstanceAttribute
            - ec2:DescribeInstanceStatus
            - ec2:DescribeInstances
            - ec2:DescribeVolumeAttribute
            - ec2:DescribeVolumeStatus
            Resource: "*"
  BackupInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: BackupRole
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::FindInMap:
        - SubnetConfig
        - VPC
        - CIDR
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
      - Key: Name
        Value: AWS Cloud Lab Backup VPC
  PublicSubnet:
    DependsOn:
    - VPC
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs: ''
      VpcId:
        Ref: VPC
      CidrBlock:
        Fn::FindInMap:
        - SubnetConfig
        - Public
        - CIDR
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
      - Key: Name
        Value: AWS Cloud Lab Backup Public Subnet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
  GatewayToInternet:
    DependsOn:
    - VPC
    - InternetGateway
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  PublicRouteTable:
    DependsOn:
    - VPC
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
  PublicRoute:
    DependsOn:
    - PublicRouteTable
    - InternetGateway
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PublicSubnetRouteTableAssociation:
    DependsOn:
    - PublicSubnet
    - PublicRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicRouteTable
  BackupServerSecurityGroup:
    DependsOn:
    - VPC
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EBS Backup Security Group
      VpcId:
        Ref: VPC
      SecurityGroupIngress: []
      Tags:
      - Key: Name
        Value: EBS Backup Security Group
#<%- include('backupEc2.yaml')%>