AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Cloud Lab - EBS Backup
Parameters:
  InstanceType:
    Description: Backup EC2 instance type
    Type: String
    Default: t2.nano
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64
    t2.medium:
      Arch: HVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-f5f41398
    us-west-1:
      HVM64: ami-6e84fa0e
    us-west-2:
      HVM64: ami-d0f506b0
    eu-west-1:
      HVM64: ami-b0ac25c3
    eu-central-1:
      HVM64: ami-d3c022bc
    ap-southeast-1:
      HVM64: ami-1ddc0b7e
    ap-northeast-1:
      HVM64: ami-29160d47
    ap-northeast-2:
      HVM64: ami-cf32faa1
    ap-southeast-2:
      HVM64: ami-0c95b86f
    sa-east-1:
      HVM64: ami-fb890097
    cn-north-1:
      HVM64: ami-05a66c68
  SubnetConfig:
    VPC:
      CIDR: 10.44.0.0/16
    Public:
      CIDR: 10.44.0.0/24
Resources:
  BackupRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: backupEbs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: s3:*
            Resource:
            - arn:aws:s3:::<%-labWorkBucket%>
            - arn:aws:s3:::<%-labWorkBucket%>/*
          - Effect: Allow
            Action: cloudformation:DeleteStack
            Resource:
              Ref: AWS::StackId
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource:
              Fn::Join:
              - ''
              - - 'arn:aws:lambda:'
                - Ref: AWS::Region
                - ":"
                - Ref: AWS::AccountId
                - ":function:AWSCloudLabTerminator"
          - Effect: Allow
            Action:
            - ec2:AttachVolume
            - ec2:DetachVolume
            - ec2:DescribeInstanceAttribute
            - ec2:DescribeInstanceStatus
            - ec2:DescribeInstances
            - ec2:DescribeVolumeAttribute
            - ec2:DescribeVolumeStatus
            Resource: "*"
  BackupInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - Ref: BackupRole
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Fn::FindInMap:
        - SubnetConfig
        - VPC
        - CIDR
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
      - Key: Name
        Value: AWS Cloud Lab Backup VPC
  PublicSubnet:
    DependsOn:
    - VPC
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs: ''
      VpcId:
        Ref: VPC
      CidrBlock:
        Fn::FindInMap:
        - SubnetConfig
        - Public
        - CIDR
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
      - Key: Name
        Value: AWS Cloud Lab Backup Public Subnet
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
  GatewayToInternet:
    DependsOn:
    - VPC
    - InternetGateway
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
  PublicRouteTable:
    DependsOn:
    - VPC
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackName
      - Key: Network
        Value: Public
  PublicRoute:
    DependsOn:
    - PublicRouteTable
    - InternetGateway
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PublicSubnetRouteTableAssociation:
    DependsOn:
    - PublicSubnet
    - PublicRouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PublicSubnet
      RouteTableId:
        Ref: PublicRouteTable
  BackupServerSecurityGroup:
    DependsOn:
    - VPC
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EBS Backup Security Group
      VpcId:
        Ref: VPC
      SecurityGroupIngress: []
      Tags:
      - Key: Name
        Value: EBS Backup Security Group

  BackupEbsServerInstance:
      Type: AWS::EC2::Instance
      DependsOn:
    #<% users.forEach(function(user,i){ %>
        - LabStorageVolume<%-i%>
    #<% }); %>
      Properties:
        ImageId: ami-29160d47
        InstanceType:
          Ref: InstanceType
        Tags:
        - Key: Name
          Value: "<%-users[0].lab%>Cleaner"
        AvailabilityZone:
          Fn::Select:
          - '0'
          - Fn::GetAZs: ''
        IamInstanceProfile:
          Ref: BackupInstanceProfile
        NetworkInterfaces:
        - GroupSet:
          - Ref: BackupServerSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId:
            Ref: PublicSubnet
        UserData:
          Fn::Base64:
            Fn::Sub:
              - |
                #!/bin/bash
                export JAVA_HOME=/usr/lib/jvm/jre
                export EC2_AMITOOL_HOME=/opt/aws/amitools/ec2
                export EC2_HOME=/opt/aws/apitools/ec2
                export PATH=/usr/local/bin:/bin:/usr/bin:/opt/aws/bin:/home/ec2-user/bin
                declare -a volumeIds=(<% users.forEach(function(user,i){ %>"${LabStorageVolume<%-i%>}" <% }); %>)

                declare -a emails=( <% users.forEach(function(user,i){ %>"<%-user.email%>" <% }); %>)
                mkdir data
                instanceId==$(curl -s http://instance-data/latest/meta-data/instance-id)

                driveLetters=(f g h i j k l m n o p)
                driveLetterIndex=0
                for i in "${!!volumeIds[@]}"; do
                    driveLetter=${!driveLetters[$driveLetterIndex % ${!#driveLetters[@]}]}
                    printf "%s\t%s\t%s\t%s\n" "$i" "${!volumeIds[$i]}" "${!emails[$i]} ${!driveLetter}"

                    ec2-attach-volume ${!volumeIds[$i]} -i $instanceId  -d /dev/sd${!driveLetter} --region ${AWS::Region}
                    DATA_STATE="unknown"
                    until [ "${!DATA_STATE}" == "attached" ]; do
                      DATA_STATE=$(aws ec2 describe-volumes \
                        --region ${AWS::Region} \
                        --filters \
                            Name=attachment.instance-id,Values=${!instanceId} \
                            Name=attachment.device,Values=/dev/sd${!driveLetter} \
                        --query Volumes[].Attachments[].State \
                        --output text)
                      sleep 5
                    done
                    lsblk
                    mount /dev/xvd${!driveLetter} data
                    aws s3 sync data "s3://${labWorkBucket}/${course}/${lab}/${!emails[$i]}" --region ${AWS::Region} --exclude *RECYCLE.BIN*
                    umount /dev/xvd${!driveLetter}
                    ec2-detach-volume ${!volumeIds[$i]} --region ${AWS::Region}
                    sleep 5s

                    let driveLetterIndex=driveLetterIndex+1
                done
                aws lambda invoke --function-name AWSCloudLabTerminator --region ${AWS::Region}  --payload '{"stackId":"${AWS::StackId}"}' outputfile.txt
                cat outputfile.txt
              - {
                <% users.forEach(function(user,i){ %>
                LabStorageVolume<%-i%>: !Ref LabStorageVolume<%-i%>,<% }); %>
                labWorkBucket: "<%-labWorkBucket%>",
                course: "<%-users[0].course.course%>",
                lab: "<%-users[0].lab%>"
                }
#<% users.forEach(function(user,i){ %>
  LabStorageVolume<%-i%>:
    Type: AWS::EC2::Volume
    DeletionPolicy: Delete
    Properties:
      SnapshotId: "<%-user.labStorageSnapshotId%>"
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs: ''
      Tags:
      - Key: Owner
        Value: "<%-user.email%>"
      - Key: AWSAccount
        Value: "<%-user.awsAccount%>"
      - Key: Name
        Value: BackupLabStorage-<%-user.email%>
#<% }); %>
