  BackupEbsServerInstance:
    Type: AWS::EC2::Instance
    DependsOn:
  #<% users.forEach(function(user,i){ %>
    - LabStorageVolume<%-i%>
  #<% }); %>
    Properties:
      ImageId: ami-29160d47
      InstanceType:
        Ref: InstanceType
      Tags:
      - Key: Name
        Value: "<%-users[0].lab%>Cleaner"
      AvailabilityZone:
        Fn::Select:
        - '0'
        - Fn::GetAZs: ''
      IamInstanceProfile:
        Ref: BackupInstanceProfile
      NetworkInterfaces:
      - GroupSet:
        - Ref: BackupServerSecurityGroup
        AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        DeleteOnTermination: 'true'
        SubnetId:
          Ref: PublicSubnet
      UserData:
        Fn::Base64:
          Fn::Join:
          - ''
          - - "#!/bin/bash\n"
            - 'export JAVA_HOME=/usr/lib/jvm/jre'
            - 'export EC2_AMITOOL_HOME=/opt/aws/amitools/ec2'
            - 'export EC2_HOME=/opt/aws/apitools/ec2'
            - 'export PATH=/usr/local/bin:/bin:/usr/bin:/opt/aws/bin:/home/ec2-user/bin'
            - 'declare -a volumeIds=( '
            - "\""
  #<% users.forEach(function(user,i){ %>
            - Ref: LabStorageVolume<%-i%>
  #<% }); %>
            - "\" "
            - ")\n"
  #          <% backupScriptLines.forEach((line,i)=>{ %>
             "<%-line%>\n",
  #          <% }); %>
            - 'aws lambda invoke --function-name AWSCloudLabTerminator --region '
            - Ref: AWS::Region
            - ' --payload ''{"stackId":"'
            - Ref: AWS::StackId
            - "\"}' outputfile.txt \n"
            - 'cat outputfile.txt'
  #    <% users.forEach(function(user,i){ %>
      <%- include('ebs.yaml', {i: i,user:user}) %>
  #    <% }); %>
