
  LabMaterialVolume<%-i%>:
    Type: AWS::EC2::Volume
    Properties:
      SnapshotId: "<%-user.labMaterialSnapshotId%>"
      AvailabilityZone:
        Fn::GetAtt:
        - Subnet
        - AvailabilityZone
      Tags:
      - Key: Name
        Value: LabMaterial-<%-user.email%>
  LabStorageVolume<%-i%>:
    Type: AWS::EC2::Volume
    DeletionPolicy: Snapshot
    Properties:
      SnapshotId: "<%-user.labStorageSnapshotId%>"
      AvailabilityZone:
        Fn::GetAtt:
        - Subnet
        - AvailabilityZone
      Tags:
      - Key: Owner
        Value: "<%-user.email%>"
      - Key: AWSAccount
        Value: "<%-user.awsAccount%>"
      - Key: Name
        Value: LabStorage-<%-user.email%>
  StudentInstance<%-i%>:
    Type: AWS::EC2::Instance
    DependsOn:
    - AttachGateway
    - Ec2KeyPairs
    Properties:
      ImageId: "<%-user.imageId%>"
      InstanceType:
        Ref: InstanceType
      KeyName: "<%-user.key%>"
      AvailabilityZone:
        Fn::GetAtt:
        - Subnet
        - AvailabilityZone
      Volumes:
      - VolumeId:
          Ref: LabStorageVolume<%-i%>
        Device: "/dev/sdg"
      - VolumeId:
          Ref: LabMaterialVolume<%-i%>
        Device: "/dev/sdh"
      Tags:
      - Key: Application
        Value:
          Ref: AWS::StackId
      - Key: Owner
        Value: "<%-user.email%>"
      - Key: AWSAccount
        Value: "<%-user.awsAccount%>"
      - Key: Name
        Value: "<%-user.email%>"
      - Key: IAMUser
        Value:
          Ref: CFNUser<%-i%>
      - Key: Password
        Value: "<%-user.password%>"
      NetworkInterfaces:
      - GroupSet:
        - Ref: InstanceSecurityGroup
        AssociatePublicIpAddress: 'true'
        DeviceIndex: '0'
        DeleteOnTermination: 'true'
        SubnetId:
          Ref: Subnet
